USE [master]
GO

/****** Object:  Database [train_station]    Script Date: 29.11.2022 16:34:10 ******/
CREATE DATABASE [train_station]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'train_station', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\train_station.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'train_station_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\train_station_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [train_station].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [train_station] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [train_station] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [train_station] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [train_station] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [train_station] SET ARITHABORT OFF 
GO

ALTER DATABASE [train_station] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [train_station] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [train_station] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [train_station] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [train_station] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [train_station] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [train_station] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [train_station] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [train_station] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [train_station] SET  ENABLE_BROKER 
GO

ALTER DATABASE [train_station] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [train_station] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [train_station] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [train_station] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [train_station] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [train_station] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [train_station] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [train_station] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [train_station] SET  MULTI_USER 
GO

ALTER DATABASE [train_station] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [train_station] SET DB_CHAINING OFF 
GO

ALTER DATABASE [train_station] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [train_station] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [train_station] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [train_station] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [train_station] SET QUERY_STORE = OFF
GO

ALTER DATABASE [train_station] SET  READ_WRITE 
GO

